function opts = trainingOptionsConfig()
opts = trainingOptions('adam', ...
    'InitialLearnRate', 1e-3, ...
    'MaxEpochs', 30, ...
    'MiniBatchSize', 4, ...
    'GradientThreshold', 1, ...
    'Plots', 'training-progress');
end